### ISSUE TITLE
sphinx fails to work with latest versions

### ISSUE THREAD

**Issue by nadiasvertex** [djungelorm/sphinx-csharp#2]
# Sphinx version: 1.7.2
# Python version: 3.6.4 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
```
# Last messages:
#   283 added, 0 changed, 0 removed
#   
#   reading sources... [  0%] changelog
#   
#   reading sources... [  0%] cs/core.article/article
#   
#   reading sources... [  1%] cs/core.article/article.enums
#   
#   reading sources... [  1%] cs/core.article/article.messages
#   
# Loaded extensions:
#   alabaster (0.7.10) from /usr/local/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.intersphinx (1.7.2) from /usr/local/lib/python3.6/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.coverage (1.7.2) from /usr/local/lib/python3.6/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.ifconfig (1.7.2) from /usr/local/lib/python3.6/site-packages/sphinx/ext/ifconfig.py
#   sphinx_csharp.csharp (unknown version) from /usr/local/lib/python3.6/site-packages/sphinx_csharp/csharp.py
#   sphinxcontrib.httpdomain (unknown version) from /usr/local/lib/python3.6/site-packages/sphinxcontrib/httpdomain.py
#   sphinx.ext.mathjax (1.7.2) from /usr/local/lib/python3.6/site-packages/sphinx/ext/mathjax.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/usr/local/lib/python3.6/site-packages/sphinx/application.py", line 331, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 338, in build_update
    'out of date' % len(to_build))
  File "/usr/local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 351, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/usr/local/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 565, in update
    self._read_serial(docnames, self.app)
  File "/usr/local/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 584, in _read_serial
    self.read_doc(docname, app)
  File "/usr/local/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 659, in read_doc
    doctree = read_doc(self.app, self, self.doc2path(docname))
  File "/usr/local/lib/python3.6/site-packages/sphinx/io.py", line 294, in read_doc
    pub.publish()
  File "/usr/local/lib/python3.6/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/local/lib/python3.6/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/usr/local/lib/python3.6/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/local/lib/python3.6/site-packages/sphinx/parsers.py", line 85, in parse
    self.statemachine.run(inputstring, document, inliner=self.inliner)
  File "/usr/local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/usr/local/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/local/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2988, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/usr/local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/local/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/usr/local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/usr/local/lib/python3.6/site-packages/sphinx/domains/__init__.py", line 237, in run
    return BaseDirective.run(self)
  File "/usr/local/lib/python3.6/site-packages/sphinx/directives/__init__.py", line 179, in run
    self.state.nested_parse(self.content, self.content_offset, contentnode)
  File "/usr/local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/local/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/usr/local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/usr/local/lib/python3.6/site-packages/sphinx/domains/__init__.py", line 237, in run
    return BaseDirective.run(self)
  File "/usr/local/lib/python3.6/site-packages/sphinx/directives/__init__.py", line 160, in run
    name = self.handle_signature(sig, signode)
  File "/usr/local/lib/python3.6/site-packages/sphinx_csharp/csharp.py", line 448, in handle_signature
    name, params = parse_attr_signature(sig)
  File "/usr/local/lib/python3.6/site-packages/sphinx_csharp/csharp.py", line 142, in parse_attr_signature
    raise RuntimeError('Attribute signature invalid, got ' + sig)
RuntimeError: Attribute signature invalid, got string Uuid
```

**Comment by nadiasvertex** [comment]
Sorry, the error was misleading. This is in my own code.
